language: rust
rust:
  - stable
  - nightly
cache: cargo
env:
  - RUST_PROJECT_DIR: todo_queue_cli
  - RUST_PROJECT_DIR: todo_queue_lib
before_script: cd $RUST_PROJECT_DIR
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
