[package]
name = "todo_queue_cli"
version = "0.1.0"
authors = ["Robin Miller <grenewodemiller@gmail.com>"]

[dependencies]
todo_queue_lib = { path = "../todo_queue_lib" }
rustyline = "1.0.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
app_dirs = "1.1.1"
failure = "0.1.1"
